name: Flag Submission
description: Submit your solved challenge flag
title: "Challenge-XX Submission â€“ YourName"
body:
  - type: input
    id: challenge
    attributes:
      label: Challenge
      placeholder: "04-aes-ecb-cutpaste"
    validations:
      required: true

  - type: input
    id: flag
    attributes:
      label: Flag
      placeholder: "FLAG{...}"
    validations:
      required: true

  - type: textarea
    id: method
    attributes:
      label: Method
      description: Short explanation (no code)
    validations:
      required: true
